const resp = {
    id: 'false_628985665498@c.us_1FE1901AB4E10F46A1599AB3198FD73C',
        body: 'Dd',
    type: 'chat',
    t: 1630052057,
    notifyName: '',
    from: '628985665498@c.us',
    to: '6285156526447@c.us',
    self: 'in',
    ack: 0,
    invis: false,
    isNewMsg: true,
    star: false,
    recvFresh: true,
    isFromTemplate: false,
    broadcast: false,
    quotedMsg: null,
    mentionedJidList: [],
    isVcardOverMmsDocument: false,
    isForwarded: false,
    labels: [],
    ephemeralOutOfSync: false,
    productHeaderImageRejected: false,
    isDynamicReplyButtonsMsg: false,
    isMdHistoryMsg: false,
    chatId: '628985665498@c.us',
    fromMe: false,
    sender: {
    id: '628985665498@c.us',
        name: 'DTP WA',
        shortName: 'DTP',
        pushname: 'Rizqy Prastya A.N',
        type: 'in',
        isBusiness: false,
        isEnterprise: false,
        statusMute: false,
        labels: [],
        formattedName: 'DTP WA',
        isMe: false,
        isMyContact: true,
        isPSA: false,
        isUser: true,
        isWAContact: true,
        profilePicThumbObj: { eurl: null, id: '628985665498@c.us', tag: null },
    msgs: null
},
    timestamp: 1630052057,
        content: 'Dd',
    isGroupMsg: false,
    isMedia: false,
    isNotification: false,
    isPSA: false,
    chat: {
    id: '628985665498@c.us',
        pendingMsgs: false,
        lastReceivedKey: {
        fromMe: false,
            remote: '628985665498@c.us',
            id: 'BF0C58F1C5E4252C2DA8E08D14016DB1',
            _serialized: 'false_628985665498@c.us_BF0C58F1C5E4252C2DA8E08D14016DB1'
    },
    t: 1630052016,
        unreadCount: 1,
        archive: false,
        isReadOnly: false,
        modifyTag: 83784,
        muteExpiration: 0,
        name: 'Christofel',
        notSpam: true,
        pin: 0,
        ephemeralDuration: 0,
        ephemeralSettingTimestamp: 0,
        msgs: null,
        kind: 'chat',
        canSend: true,
        isGroup: false,
        formattedTitle: 'DTP WA',
        contact: {
        id: '628985665498@c.us',
            name: 'DTP WA',
            shortName: 'DTP',
            pushname: 'Rizqy Prastya A.N',
            type: 'in',
            isBusiness: false,
            isEnterprise: false,
            statusMute: false,
            labels: [],
            formattedName: 'DTP WA',
            isMe: false,
            isMyContact: true,
            isPSA: false,
            isUser: true,
            isWAContact: true,
            profilePicThumbObj: [Object],
            msgs: null
    },
    groupMetadata: null,
        presence: { id: '628985665498@c.us', chatstates: [] },
    isOnline: true,
        participantsCount: 1
},
    isOnline: true,
        quotedMsgObj: null,
    mediaData: {}
}
